server:
  port: 19001
spring:
  application:
    name: pec-admin-user
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.60.127:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/pec_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.yxinmiracle.model.services.pojos
host: https://pic.yxinmiracle.com
logging:
  level:
    com.yxinmiracle: debug