server:
  port: 19006
spring:
  application:
    name: pec-admin-search
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.60.127:8848
  rabbitmq:
    host: 192.168.211.132  #mq的服务器地址
    username: guest #账号
    password: guest #密码
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.yxinmiracle.model.search.pojos
host: https://pic.yxinmiracle.com
logging:
  level:
    com.yxinmiracle: debug
mq:
  search:
    searchExchange: searchExchange
    queue:
      addChoiceQuestion: search.add.choiceQuestion
      addAnswerQuestion: search.add.answerQuestion
      addQuestionTag: search.add.questionTag
    routing:
      addChoiceQuestionRouting: search.add.choiceQuestion
      addAnswerQuestionRouting: search.add.answerQuestion
      addQuestionTagRouting: search.add.questionTag